version: '3.9'

x-common-environment: &common-environment
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_SCHEMAS: la-vie
  SPRING_FLYWAY_SCHEMAS: la-vie

services:
  spring-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      <<: *common-environment
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgresql:5432/psych-clinic
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: la-vie
    depends_on:
      db-postgresql:
        condition: service_healthy
    networks:
      - app-network

  db-postgresql:
    image: postgres:latest
    hostname: db-postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: psych-clinic
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
