spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    schemas: la-vie
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  error:
    include-message: always
