spring:
  profiles:
    active: dev

management:
  endpoint:
    health:
      show-details: always

server:
  error:
    include-message: always
  servlet:
    contextPath: /api

springdoc:
  swagger-ui:
    path: /swagger-ui
  version: 0.0.1