spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psych-clinic
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: la-vie
    schemas: la-vie
  flyway:
    schemas: la-vie

server:
  error:
    include-message: always
  servlet:
    contextPath: /api