spring:
  datasource:
    url: jdbc:postgresql://db-postgresql:5432/psych-clinic
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: la-vie
    url: jdbc:postgresql://db-postgresql:5432/psych-clinic
    user: postgres
    password: postgres
