spring:
  profiles:
    active: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    hibernate:
      ddl-auto: create-drop
      default_schema: ${DATABASE_SCHEMA}
      format_sql: true
    show-sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  management:
    endpoint:
      health:
        show-details: always
server:
  error:
    include-message: always

  servlet:
      contextPath: /api
